# Generated by Django 4.0.3 on 2022-03-27 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('louvre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='local_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
